#!/usr/bin/env bash
# 1-install_nginx_web_server
# Written by Ignatius K <ignatiuskisekka@gmail.com>
#
# Script that installs and starts nginx on server
#
# Requirement:
# 	- utils already available; sudo, ufw

apt-get update -y
apt-get install nginx -y

cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.cp

echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

service nginx restart
