#!/usr/bin/env bash
# 0-custom-http_response_header
# Written by Ignatius K <ignatiuskisekka@gmail.com>
#
# Script configures default header on Nginx

CUSTOM_HEADER_CONF="error_page 404 \/custom_404.html;\n location \/redirect_me {\n return 301 \$scheme:\/\/www.google.com;"
DEFAULT_FILE="/etc/nginx/sites-available/default"


host=$(hostname)
SERVED_HEADER_CONF="server {\n\tadd_header X-Served-By $host;"

apt-get update -y
apt-get install nginx -y

echo "Hello World!" > /usr/share/nginx/html/index.html

mkdir -p /var/www/html
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html

sudo sed -i -E "s/^[^#]+location \/ \{/$CUSTOM_HEADER_CONF/" $DEFAULT_FILE
sudo sed -i -E "s/^server \{/$SERVED_HEADER_CONF/" $DEFAULT_FILE
sudo service nginx start
