#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header
# HTTP response contains a custom header (on web-01 and web-02)
var=$(hostname)


CUSTOM_HEADER_CONF="error_page 404 \/custom_404.html;\n location \/redirect_me {\n return 301 \$scheme:\/\/www.google.com;"

SERVED_HEADER_CONF="server {\n\tadd_header X-Served-By $var;"

apt-get update -y
apt-get install nginx -y

echo "Hello World!" > /usr/share/nginx/html/index.html

mkdir -p /var/www/html

echo "Ceci n'est pas une page" > /var/www/html/custom_404.html

sudo sed -i -E "s/^[^#]+location \/ \{/$CUSTOM_HEADER_CONF/" /etc/nginx/sites-available/default

sudo sed -i -E "s/^server \{/$SERVED_HEADER_CONF/" /etc/nginx/sites-available/default

sudo service nginx start
