#!/usr/bin/env bash
# Written by Ignatius K <ignatiuskisekka@gmail.com>
#
# Script that configures HAProxy on Ubuntu server

apt-get -y update
apt-get -y install --no-install-recommends software-properties-common
apt-get -y install haproxy=2.8.\*

# cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.copy
HA_PROXY_FILE='/etc/default/haproxy'
if [ "$(grep -Eco '^ENABLED=[01]$' < $HA_PROXY_FILE)" -gt 0 ]; then
	sed -i 's/^ENABLED=0$/ENABLED=1/' "$HA_PROXY_FILE"
else
	echo 'ENABLED=1' >> $HA_PROXY_FILE
fi

echo -e '
frontend alexa_frontend
        bind *:80
        default_backend alexa_main_backend

backend alexa_main_backend
        balance roundrobin
        server 486431-web-01 54.152.221.218:80 check
        server 486431-web-02 54.146.70.187:80 check
' >> /etc/haproxy/haproxy.cfg

if [ "$(pgrep -c haproxy)" -le 0 ]; then
	service haproxy start
else
	service haproxy restart
fi
