#!/usr/bin/env bash
#  2-show_your_bash_pid
#  shellcheck disable=SC2009
#  Written by Ignatius K <ignatiuskisekka@gmail.com>
#  Copyright (C) 2024 Ignatius K
#
#  This script display Bash-like processes
#####################################

ps aux -H | grep "bash"
