#!/usr/bin/env bash
#  5-dont_stop_me_now
#  Written by Ignatius K <ignatiuskisekka@gmail.com>
#
#  Script that stops "4-to_infinity_and_beyond" process

pid=$(pgrep -f 4-to_infinity_and_beyond)
kill "$pid"
