#!/usr/bin/env bash
#  7-highlander
#  Written by Ignatius K <ignatiuskisekka@gmail.com>
#  Copyright (C) 2024 Ignatius K
#
#  Script displays text indefinitely
#
#  Requirements:
#  	- Sleep 2 in between each iteration
#  	- On receiving a `SIGTERM` signal, display "I am invincible!!!"


function handle_sigterm() {
	echo "I am invincible!!!"
}


trap "handle_sigterm" SIGTERM


while true
do
	echo "To infinity and beyond"
	sleep 2
done
