#!/usr/bin/env bash
#  for_best_school
#  Written by Ignatius K <ignatiuskisekka@gmail.com>

#  A script that displays "Best School"
#+ 10 times
####################################################

n=10
for (( i=0; i<10; i++ )); do
	echo "Best School"
done
