#!/usr/bin/env bash
#  10-fizzbuzz
#  Written by: Ignatius K <ignatiuskisekka@gmail.com>
#
#  Script that displays from 1 to 100
#+ when number is multiple of 3 and 5, displays FizzBuzz
#+ whem multiple of 3, Fizz, when multiple of 5, Buzz
#####################################################

for i in {1..100}
do
	if (( i % 15 == 0 ))
	then
		echo "FizzBuzz"
	elif (( i % 3 == 0 ))
	then
		echo "Fizz"
	elif (( i % 5 == 0 ))
	then
		echo "Buzz"
	else
		echo "$i"
	fi
done
