#!/usr/bin/env bash
#  10-fizzbuzz
#  Written by: Ignatius K <ignatiuskisekka@gmail.com>
#
#  Script that displays from 1 to 100
#+ when number is multiple of 3 and 5, displays FizzBuzz
#+ whem multiple of 3, Fizz, when multiple of 5, Buzz
#####################################################


function fizzy() {
	if [[ $(($1 % 3)) == 0 ]]; then
		echo "Fizz"
	fi
}

function buzzy() {
	if [[ $(($1 % 5)) == 0 ]]; then
		echo "Buzz"
	fi
}

function fizzyBuzzY() {
	if { fizzy "$1" && buzzy "$1"; }; then
		echo "FizzBuzz"
	fi
}


i=1
n=100

for (( ; i<n; i++ )), do
	if [ fizzyBuzzY $i ]; then

		...
done
