#!/usr/bin/env bash
#  8-for_ls
#  Written by Ignatius K <ignatiuskisekka@gmail.com>
#
#  A script that displays content of current directory
#+ in list format, only the name after first dash (-)
#* is displayed

for file in $(ls)
do
	echo "$file" | cut -d "-" -f 2
done
