#!/usr/bin/env bash
#  0-change_your_home_IP
#  Written by Ignatius K <ignatiuskisekka@gmail.com>
#  Copyright (C) 2024
#
#  Script that configures Ubuntu server
#
#  Requirements:
#    - localhost resolves to 127.0.0.2
#    - facebook.com resolves to 8.8.8.8

touch ~/hosts.new
echo "127.0.0.2		localhost" >> ~/hosts.new
echo "8.8.8.8	facebook.com" >> ~/hosts.new

sudo cp /etc/hosts /etc/hosts.old
sudo cp ~/hosts.new /etc/hosts
