#!/usr/bin/env bash
#  1-show_attached_IPs
#  Written by Ignatius K <ignatiuskisekka@gmail.com>
#
#  Script tnat displays all active IPv4 IPs on the machine

ifconfig | grep -Eo "inet (addr:)?([0-9]*\.){3}[0-9]*" | cut -c 6-
